/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
/*objective :
 *  1) manually pend the pending bit for USART3 IRQ number in NVIC
 *  2) Enable the USART3 IRQ number in NVIC
 **/

#include <stdio.h>
#include <stdint-gcc.h>

#define USART3_IRQNO 39


int main(void)
{
//	 manually pend the pending bit for USART3 IRQ number in NVIC
	 uint32_t *pISPR1 = (uint32_t*)0XE000E204; //Creating pointer to the address position of ISPR1
	 *pISPR1 |= (1 <<(USART3_IRQNO % 32));   // writing 1 at 7th position of ISPR1

//   enable the USART IRQ number
	 uint32_t *pISER1 = (uint32_t*)0xE000E104;
	 *pISER1 |= (1 <<(USART3_IRQNO % 32));  //this line will raise the interrupt and call goes to the USART3_IRQHandler


	for(;;);
}

//	Implement ISR
void USART3_IRQHandler(void){
	printf("in USART3 isr \n");
}

/*In real world the pending is done automatically but here we are doing it manually
 * */
