#include "main.h"

// Function prototypes
void SystemClock_Config(void);
static void MX_GPIO_Init(void);

int main(void) {
  // Initialize the HAL Library
  HAL_Init();

  // Configure the system clock
  SystemClock_Config();

  // Initialize all configured peripherals
  MX_GPIO_Init();

  // Main loop
  while (1) {
    // Toggle the on-board LED
    HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
    // Delay for 500 milliseconds
    HAL_Delay(500);
  }
}

// System Clock Configuration
void SystemClock_Config(void) {
  // (The content of this function is usually auto-generated by STM32CubeMX)
}

// GPIO Initialization Function
static void MX_GPIO_Init(void) {
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  // Enable GPIOC clock
  __HAL_RCC_GPIOC_CLK_ENABLE();

  // Configure GPIO pin: PC13
  GPIO_InitStruct.Pin = GPIO_PIN_13;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
}

void Error_Handler(void) {
  // (Optional) Handle errors
}
