/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ALIAS_BASE 0x22000000U     // U stands for unsigned int
#define BITBAND_BASE 0x20000000U

int main(void)
{
    uint8_t *ptr = (uint8_t*)0x20000200;  //Assign ptr to point at this address

    *ptr = 0xff;     // Assign value to that address pointed by ptr

    //Normal method

    *ptr &= ~(1 << 7);  //Making 7th bit 0   Ans: 0111_1111][value at location of ptr] *Not the address itself

    //reset to 0xff
    *ptr = 0xff;

    //Bit Band method
    //alias_address=alias_base +(32*(baseband_memory_addr - bitband_base))+ (bit_position)*4

    uint8_t *alias_addr=(uint8_t*)(ALIAS_BASE+(32*(0x20000200 - BITBAND_BASE))+ 4*7);

    //clearing the 7th bit of addr 0x20000200
    *alias_addr = 0;




}
