/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


//  This function executes in THREAD MODE of the processor
void generate_interupt(){
	uint32_t *pSTIR = (uint32_t*)0xE000EF00;   //STIR = Software trigger interrupt pointer
	uint32_t *pISER0 = (uint32_t*)0xE000E100;  //ISER0 =Interrupt set enable register 0

	//enable IRQ3 interrupt
	*pISER0 |= (1<<3);     //    '1 << 3'  shifts the value 1 three positions to the left,  4th bit (IRQ3) is set to 1.

	//Generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);   //    3 & 0x1FF isolates the least significant 8 bits of the value 3, which represents IRQ3.

}

  //  This function executes in THREAD MODE of the processor
int main(void)
{
	printf("IN Thread mode:Before interrupt \n");

	generate_interupt();

	printf("In Thread mode ; After interrupt \n");
    /* Loop forever */
	for(;;);
}

//This function(ISR) executes in HANDLER MODE of processor
void RTC_WKUP_IRQHandler(void){
	printf("In handler mode : ISR \n");
}

/*Note :
 * Enabling IRQ3: The line *pISER0 |= (1 << 3); sets the 4th bit in the Interrupt Set-Enable Register 0 (ISER0),
 * enabling IRQ3 in the NVIC (Nested Vectored Interrupt Controller).

  Triggering IRQ3: The line *pSTIR = (3 & 0xFF); writes the value 3 to the Software Trigger Interrupt Register (STIR),
  manually generating an IRQ3 interrupt via software.*/
